name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: compile
      run: lein uberjar
    - name: Status
      run: echo Compiled Successful
    
    - name: Build and Push Docker Image
      uses: HurricanKai/Publish-Docker-Github-Action@master
      with:
        name: gatu/github-xtn-repo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        snapshot: true
        tagging: true
        
    - name: Checkout from the repo
      uses: actions/checkout@v2.4.2
      
    - name: clj-kondo checks  
      uses: DeLaGuardo/clojure-lint-action@master
      with:
        clj-kondo-args: --lint src
        github_token: ${{ secrets.THEHUB_TOKEN }}








