name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
    - name: compile
      run: lein uberjar
    - name: Status
      run: echo Compiled Successful
